/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Vertice;
import com.sun.glass.events.KeyEvent;
import javax.swing.JFrame;

/**
 *
 * @author samue
 */
public class AddVertice extends javax.swing.JFrame {

    static public MainForm enviaVertice;

    /**
     * Creates new form addVertice
     */
    public AddVertice(MainForm pai) {
        initComponents();
        enviaVertice = pai;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        nomeVertice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        posEixoX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        posEixoY = new javax.swing.JTextField();
        terminal = new javax.swing.JCheckBox();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setTitle("Adicionar vertice");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Insira o nome do Vertice:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, -1));

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 100, -1));

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 100, -1));

        nomeVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeVerticeActionPerformed(evt);
            }
        });
        getContentPane().add(nomeVertice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 310, -1));

        jLabel2.setText("Posição eixo X:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, -1));

        posEixoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posEixoXActionPerformed(evt);
            }
        });
        getContentPane().add(posEixoX, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 310, -1));

        jLabel3.setText("Posição eixo Y:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, -1));

        posEixoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posEixoYActionPerformed(evt);
            }
        });
        posEixoY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                posEixoYKeyPressed(evt);
            }
        });
        getContentPane().add(posEixoY, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 310, -1));

        terminal.setText("Terminal");
        terminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminalActionPerformed(evt);
            }
        });
        getContentPane().add(terminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        getAccessibleContext().setAccessibleName("df");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean verificarErrosDeTipo() {
        try {
            nomeVertice.getText();
            Integer.parseInt(posEixoX.getText());
            Integer.parseInt(posEixoY.getText());
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private boolean verificarCasaVazia() {
        return nomeVertice.getText() == "" || posEixoX.getText() == "" || posEixoY.getText() == "";
    }

    private boolean verificarSeOVerticeExiste(Vertice v) {
        return enviaVertice.getGrafo().get(v.getNomeTerminal()) != null;
    }

    private Vertice gerarVertice() {
        String nomeDoVertice = nomeVertice.getText();
        int posX = Integer.parseInt(posEixoX.getText());
        int posY = Integer.parseInt(posEixoY.getText());
        boolean term = terminal.isSelected();
        Vertice vrt = new Vertice(nomeDoVertice, term, posX, posY);
        return vrt;
    }

    private void salvarNoGrafo(Vertice vrt) {
        enviaVertice.gerarVertice(vrt);
        this.dispose();
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        salvarVertice();
        clear();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void salvarVertice() {
        if (verificarErrosDeTipo() && !verificarCasaVazia()) {
            Vertice v = gerarVertice();
            if (!verificarSeOVerticeExiste(v)) {
                salvarNoGrafo(v);
            }
        }
    }

    private void nomeVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeVerticeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeVerticeActionPerformed

    private void posEixoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posEixoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posEixoXActionPerformed

    private void posEixoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posEixoYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posEixoYActionPerformed

    private void terminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terminalActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (nomeVertice.getText() == "" && posEixoX.getText() == "" && posEixoY.getText() == "") {
            System.out.println("passou");
        }
        clear();


    }//GEN-LAST:event_btnCancelActionPerformed

    private void clear() {
        nomeVertice.setText("");
        posEixoX.setText("");
        posEixoY.setText("");
        terminal.setSelected(false);
    }
    private void posEixoYKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_posEixoYKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvarVertice();
        }
    }//GEN-LAST:event_posEixoYKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVertice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVertice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVertice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVertice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVertice(enviaVertice).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nomeVertice;
    private javax.swing.JTextField posEixoX;
    private javax.swing.JTextField posEixoY;
    private javax.swing.JCheckBox terminal;
    // End of variables declaration//GEN-END:variables

}
